version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: InfSys_lab
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student_itmo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
